version: '3.5'

networks:
  eventnet:

services:
  events:
    # image: benhutchins/taiga-events
    build: .
#    restart: always
    networks:
      - eventnet
    labels:
      - traefik.enable=false
    expose:
      - 80
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:80/conf.json"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 0s

